### ISSUE TITLE
Question about RevlogEntry mapping

### ISSUE THREAD

**Issue by dae** [open-spaced-repetition/fsrs-optimizer-burn#37]
@L-M-Sherlock @asukaminato0721 I'm a bit confused by part of the revlog importing:

This line adds one to all revlog types. Since the minimum type is 0 before this, the minimum type afterwards will be 1:

https://github.com/open-spaced-repetition/fsrs-optimizer-burn/blob/e735558254ccac562cd9fae8f7778d660bfc9e30/src/convertor.rs#L81

This line looks like it will never match, since review_kind will never be 0:

https://github.com/open-spaced-repetition/fsrs-optimizer-burn/blob/e735558254ccac562cd9fae8f7778d660bfc9e30/src/convertor.rs#L103

Is there something wrong here? Maybe it would be clearer without adding 1 to everything?

**Comment by L-M-Sherlock** [comment]
I want to keep consistency among the Python version and Rust version. Here is the schema:

Column Name | Data Type | Description | Constraints
-- | -- | -- | --
review_state | integer | The state of the card at the time of review. This describes the learning phase of the card | Optional, Values: {0 (New), 1 (Learning), 2 (Review), 3 (Relearning)}

https://github.com/open-spaced-repetition/fsrs-optimizer#review-logs-schema

**Comment by dae** [comment]
Won't the current Rust code (the second line I showed) _always_ fail, because review_kind will never be 0 after the addition? What if instead of changing the numbers, you used constants like "Review" instead of comparing numbers? Then it should be clear in both.

**Comment by dae** [comment]
Eg const Review = 1; if review_kind == Review { ... }

**Comment by L-M-Sherlock** [comment]
Oops. I made a mistake. I will fix it. And use const.

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/95694b787bb71ac9883db1201af09e334ee5ee0b/src/fsrs_optimizer/fsrs_optimizer.py#L372-L373

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/95694b787bb71ac9883db1201af09e334ee5ee0b/src/fsrs_optimizer/fsrs_optimizer.py#L381

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/95694b787bb71ac9883db1201af09e334ee5ee0b/src/fsrs_optimizer/fsrs_optimizer.py#L398-L398

**Comment by dae** [comment]
Closed by #38
