### ISSUE TITLE
[TODO] feature: weight clipper

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-optimizer-burn#4]
Python implementation:
https://github.com/open-spaced-repetition/fsrs-optimizer/blob/95694b787bb71ac9883db1201af09e334ee5ee0b/src/fsrs_optimizer/fsrs_optimizer.py#L100-L120

**Comment by L-M-Sherlock** [comment]
- https://github.com/burn-rs/burn/issues/662

**Comment by L-M-Sherlock** [comment]
#9 partially implement weight clipper. The next step is calling it in the iteration loops of training. It would require https://github.com/burn-rs/burn/issues/662.

**Comment by dae** [comment]
I think the path forward may be implementing our own training loop. I've reached out to Nathaniel, so recommend we wait to hear back from him before making further changes here.

**Comment by dae** [comment]
Nathaniel has said he'll be able to take a look at the repo on Thursday (maybe Friday in Australia/China). If you have any questions or issues about the use of Burn in this project, creating an issue in this repo about them before then may be helpful.

**Comment by L-M-Sherlock** [comment]
Thanks. I have opened several issues to record them.

**Comment by dae** [comment]
Nathaniel has said he'd like to have a chat with you; I suggested he contact you on the email address posted on your GitHub.
