### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dae** [open-spaced-repetition/fsrs-optimizer-burn#43]
@L-M-Sherlock I presume this will be licensed as MIT like your other repos; if so, please add this line to the Cargo.toml file, and add the LICENSE file to the repo:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index c9cd01d..6d8e711 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -2,6 +2,7 @@
 name = "fsrs-optimizer-rs"
 version = "0.1.0"
 edition = "2021"
+license = "MIT"
```

**Comment by dae** [comment]
It may also be worth changing fsrs-optimizer-rs to fsrs-optimizer, since it's redundant when importing crates inside Rust.

**Comment by L-M-Sherlock** [comment]
What about AGPL v3, like Anki's main license?

**Comment by L-M-Sherlock** [comment]
OK. I prefer to use BSD-3 (same to https://github.com/open-spaced-repetition/fsrs-optimizer).

**Comment by dae** [comment]
Sure, that would be fine too

**Comment by dae** [comment]
@asukaminato0721 @GraesonB please confirm you're ok with your contributions being under that license

**Comment by L-M-Sherlock** [comment]
And @Luc-Mcgrady

**Comment by GraesonB** [comment]
Works for me.

**Comment by dae** [comment]
@Luc-Mcgrady if you wouldn't mind stating so in a comment, that would be appreciated

**Comment by Luc-Mcgrady** [comment]
Yes I would be fine with this.
