### ISSUE TITLE
[TODO] feature: mini-batch & sequence-padding

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-optimizer-burn#5]
The current version doesn't support batch_size > 1, because:

https://github.com/open-spaced-repetition/fsrs-optimizer-burn/blob/6765d1aa36c752b724bc8b4144ab3952007ce179/src/dataset.rs#L35-L40

https://github.com/open-spaced-repetition/fsrs-optimizer-burn/blob/6765d1aa36c752b724bc8b4144ab3952007ce179/src/dataset.rs#L59

Tensor::cat() requires all tensors to have the same shape. But in current version, the length of `t_history` is various.

Python implementation:

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/95694b787bb71ac9883db1201af09e334ee5ee0b/src/fsrs_optimizer/fsrs_optimizer.py#L135

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/95694b787bb71ac9883db1201af09e334ee5ee0b/src/fsrs_optimizer/fsrs_optimizer.py#L176-L184

**Comment by dae** [comment]
I'm far out of my comfort zone here, so chances are this is not correct, but would an approach something like this work where the remaining values are padded with 0?

```diff
 impl<B: Backend> Batcher<FSRSItem, FSRSBatch<B>> for FSRSBatcher<B> {
-    fn batch(&self, items: Vec<FSRSItem>) -> FSRSBatch<B> {
+    fn batch(&self, mut items: Vec<FSRSItem>) -> FSRSBatch<B> {
+        let pad_size = items.iter().map(|i| i.t_history.len()).max().unwrap();
+        for item in &mut items {
+            item.t_history.resize(pad_size, 0);
+            item.r_history.resize(pad_size, 0);
+        }
```
