### ISSUE TITLE
Learning Rust

### ISSUE THREAD

**Issue by cjdduarte** [open-spaced-repetition/fsrs-optimizer-burn#6]
I'm starting to learn Rust and as soon as possible, I'd like to contribute to the project.

What are the initial motivations for the project? Where do you intend to integrate it?

**Comment by L-M-Sherlock** [comment]
Motivation: We plan to integrate [FSRS](https://github.com/open-spaced-repetition/fsrs4anki), a modern spaced repetition algorithm, into [Anki](https://github.com/ankitects/anki), which requires a localized optimization module to train the parameters from users' review logs.

For more details, please see:
- https://github.com/ankitects/anki/issues/2443
- https://github.com/open-spaced-repetition/fsrs-optimizer-tiny/issues/2

**Comment by dae** [comment]
Mind if we close this @cjdduarte, or did you have further questions?

**Comment by cjdduarte** [comment]
sorry. can close
